<a href="https://colab.research.google.com/github/xyziiee/CCST101-Week-1/blob/main/students.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **My First R Program**

**1.Print**

In [10]:
print("I Love R Programming")

cat("R", "Program")

[1] "I Love R Programming"
R Program

**2.Variables & Data Types**

In [9]:
myString <- "I Love R Programming"
wholeNum <- 10
floatingNum <- 9.9
isBool <- TRUE

print(myString)

class(myString)
class(wholeNum)
class(floatingNum)
class(isBool)

[1] "I Love R Programming"

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

**3.Numerical Operations**

In [43]:
x <- 10
y <- 2

add <- x + y #Addition
sub <- x - y #Subtraction
mul <- x * y #Multiplication
div <- x / y #Division
mod <- x %% y #Modulus
exp <- x ^ y #Exponent

print(add)
print(sub)
print(mul)
print(div)
print(mod)
print(exp)

[1] 12
[1] 8
[1] 20
[1] 5
[1] 0
[1] 100

**4.User Input**

In [39]:
name <- readline("Enter Name: ")

cat("Hello" , name,"!","Welcome to the R Programming")

Enter Name: Becca
Hello Becca ! Welcome to the R Programming

**5.Decision Making**

In [30]:
grade <- 80

if (grade < 75 ){
  print("Failed")
}else {
  print("Passed")
}

[1] "Passed"

**6.Loop**

In [41]:
for (i in 1:6){
  print (i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6

**7.Functions**

In [47]:
addNumber <- function(a,b){
  return(a+b)
}

addNumber(10,5)

[1] 15

**8.Vectors**

In [53]:
grades <- c(99,80,98,97,95)

grades

cat("MEAN: ", mean(grades))
cat("\nMAX: ",max(grades))
cat("\nMIN: ",min(grades))
cat("\nLENGTH: ",length(grades))
cat("\nMEDIAN: ",median(grades))
summary(grades)

[1] 99 80 98 97 95

MEAN:  93.8
MAX:  99
MIN:  80
LENGTH:  5
MEDIAN:  97

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   80.0    95.0    97.0    93.8    98.0    99.0

**9.Matrices**

In [55]:
A <- matrix(c(1,2,3,4,5,6),nrow=2)
A

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

**10.Lists**

In [60]:
students <- list(
  Name = "Becca" ,
  Course = "BSCS" ,
  Grade = 95
)

students

$Name
[1] "Becca"

$Course
[1] "BSCS"

$Grade
[1] 95

**11.DataFrame**

In [61]:
students <- data.frame(
  name = c("Becca", "Alexa", "Thea"),
  course = c("BSCS", "BSIT", "BSBA"),
  grade = c(95, 75, 80)
)

students

  name  course grade
1 Becca BSCS   95
2 Alexa BSIT   75
3 Thea  BSBA   80

**12.Write to CSV**

In [62]:
write.csv(students, "students.csv")

**13.Read CSV File**

In [64]:
data <- read.csv("students.csv")

head(data)
summary(data)

  X name  course grade
1 1 Becca BSCS   95
2 2 Alexa BSIT   75
3 3 Thea  BSBA   80

       X              name         course      grade
 Min.   :1.0   Length   :3   Length   :3   Min.   :75.00
 1st Qu.:1.5   N.unique :3   N.unique :3   1st Qu.:77.50
 Median :2.0   N.blank  :0   N.blank  :0   Median :80.00
 Mean   :2.0   Min.nchar:4   Min.nchar:4   Mean   :83.33
 3rd Qu.:2.5   Max.nchar:5   Max.nchar:4   3rd Qu.:87.50
 Max.   :3.0                               Max.   :95.00